### ISSUE TITLE
Encountered unknown tag 'secret'

### ISSUE THREAD

**Issue by ooduor** [websauna/cookiecutter-websauna-addon#1]
* cookiecutter-websauna-addon version:
* Python version: 3.5

### Description

Doing the cookiecutter installation bit. All goes well until the last step. I noticed in the stack trace below that cookiecutter was running on py2.7.

### What I Did

```
(venv) anthony@samaritan:/opt/mapylons/websauna/websauna.j2secret$ cookiecutter gh:websauna/cookiecutter-websauna-addon
Cloning into 'cookiecutter-websauna-addon'...
remote: Counting objects: 92, done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 92 (delta 27), reused 81 (delta 16), pack-reused 0
Unpacking objects: 100% (92/92), done.
Checking connectivity... done.
full_name [Amazing Team]: Me San
email [team@mycompany.com]: my@email.com
company [Websauna]: Me and Co. Ltd                   
github_username [websauna]: highPriestLOL
project_name [My Package]: Stuff Addon       
project_short_description [A nice and short description.]: Addon for managing stuff
tags [python package websauna pyramid]: websauna python pyramid gallery photos media
repo_name [websauna.package]: meandco.stuff
namespace [meandco]: 
package_name [stuff]: 
release_date [today]: 
year [2017]: 
version [1.0.0a1]: 
Traceback (most recent call last):
  File "/usr/bin/cookiecutter", line 9, in <module>
    load_entry_point('cookiecutter==1.3.0', 'console_scripts', 'cookiecutter')()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cookiecutter/cli.py", line 100, in main
    config_file=user_config
  File "/usr/lib/python2.7/dist-packages/cookiecutter/main.py", line 131, in cookiecutter
    context['cookiecutter'] = prompt_for_config(context, no_input)
  File "/usr/lib/python2.7/dist-packages/cookiecutter/prompt.py", line 126, in prompt_for_config
    val = render_variable(env, raw, cookiecutter_dict)
  File "/usr/lib/python2.7/dist-packages/cookiecutter/prompt.py", line 86, in render_variable
    template = env.from_string(raw)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 862, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 565, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'secret'.
```

**Comment by ericof** [comment]
As discussed on Glitter, we support cookiecutter on Python 3.x, that is probably the reason you were not able to use websauna.j2secret
